
version: "3.4"
services:
    web:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "DipperDipso1%"
            ACCEPT_EULA: "Y"



# version: '3.7'

# services:
#     web:
#         build: .
#         ports:
#             - "8090:80"
    #     depends_on:
    #         - db
    # db:
    #     image: "mcr.microsoft.com/mssql/server"
    #     environment:
    #         SA_PASSWORD: "Your_password123"
    #         ACCEPT_EULA: "Y"
    # birderdb:
    #    image: MyLocalRegistry:5000/birderdb-image
    #    build:
    #      context: .
    #      dockerfile: BirderDBDocker.txt


