version: '3.4'
services:
  birder:
    image: ${DOCKER_REGISTRY-}birder
    build:
      context: .
      dockerfile: Birder/Dockerfile
    #environment:
     # - DB_PW
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server
    volumes:
      - mssql-server-julie-data:/var/opt/mssql/data
    environment:
      SA_PASSWORD: "utepura0M9" #"${DB_PW}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
volumes:
  mssql-server-julie-data: {}



