version: '3.7'

services:
  birderweb:
    image: ${DOCKER_REGISTRY-}birderweb
    build:
      context: .
      dockerfile: Dockerfile #DataAPIDocker/Dockerfile
    environment:
      - DB_PW
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "${DB_PW}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

      
#   db:
#     image: mcr.microsoft.com/mssql/server
#     volumes:
#       - mssql-server-julie-data:/var/opt/mssql/data
#     environment:
#       SA_PASSWORD: "DipperDipso1%" #"${DB_PW}"
#       ACCEPT_EULA: "Y"
#     ports:
#       - "1433:1433"
# volumes:
#   mssql-server-julie-data: {}

# services:
#     web:
#         build: .
#         ports:
#             - "8080:80"
    #     depends_on:
    #         - db
    # db:
    #     image: "mcr.microsoft.com/mssql/server"
    #     environment:
    #         SA_PASSWORD: "Your_password123"
    #         ACCEPT_EULA: "Y"
    # birderdb:
    #    image: MyLocalRegistry:5000/birderdb-image
    #    build:
    #      context: .
    #      dockerfile: BirderDBDocker.txt


